version: '3.8'
services:
  quiz-game:
    build: .
    image: quiz-game:1.0
    container_name: quiz-game-container
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json